### PR TITLE
Form Validation Added Javascript - Pull Request

### PR DESCRIPTION
**Pull request by HtetWaiYan7191**
### This pull request includes the following changes made by @kit0-0 and @HtetWaiYan7191 

1. Add span error message to show erros .
2. Style error messages.
3. Add javascript for form validation.

These changes aim to improve the user experience on the contact me form by implementing a validation.

### CODE REVIEW

**Review by LionRouge1 — CHANGES_REQUESTED** [review]
Hi @HtetWaiYan7191 & @kit0-0, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost

## Highlights
- Good job showing the error message close to the submit button :+1: 
- Great job with the implementing the validation :100: 

## Required Changes ♻️
- [x] Since you are using JavaScript in this project, kindly use the [JavaScript + HTML + CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css-js) for your project.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by HtetWaiYan7191** [comment]
@LionRouge1 Hello Mrs. with all due respect, I think I use the right linter for HTML CSS and javascript can you please explain me how should I change? I also added linters for javascript already.  Can you please more explain to me . Thank you very Much 🙇

**Comment by HtetWaiYan7191** [comment]
Sorry for bothering you @LionRouge1 I know how to update my code with the help of my learning partner @kit0-0 . Thank you very much @kit0-0 😁

**Review by BregornOriginal — APPROVED** [review]
Hi @HtetWaiYan7191 

Your project is complete!  There is nothing else to say other than... it's time to merge it 

Congratulations! 

approve-applause

## Highlights

✅ Linters are passing
✅ Good work implementing changes requested by the previous reviewer

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

**Pull request merged**
